name: Build & Push Docker image

on: [ push ]

env:
  IMAGE_NAME: todoist-export
  REF: "refs/heads/main"

jobs:
  publish:
    runs-on: ubuntu-latest
    if: gitea.ref == ${{ env.REF }}
    steps:
      - name: Checkout
        uses: https://github.com/actions/checkout@v4
      - name: Set up Docker Buildx
        uses: https://github.com/docker/setup-buildx-action@v3
      - name: Login to private registry
        uses: docker/login-action@v3
        with:
          registry: https://${{ secrets.DOCKER_REGISTRY_HOST}}
          username: ${{ secrets.DOCKER_REGISTRY_USER}}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
      - name: Build and push Docker image
        uses: https://github.com/docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: "${{ secrets.DOCKER_REGISTRY_HOST }}/${{ env.IMAGE_NAME }}:${{gitea.sha}},${{ secrets.DOCKER_REGISTRY_HOST }}/${{ env.IMAGE_NAME }}:latest"
